services:
  softether:
    image: ghcr.io/yude/softethervpn-docker:master
    restart: always
    network_mode: host
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - type: bind
        target: "/usr/local/bin/packet_log"
        source: "./data/packet_log"
      - type: bind
        target: "/usr/local/bin/security_log"
        source: "./data/security_log"
      - type: bind
        target: "/usr/local/bin/server_log"
        source: "./data/server_log"
      - type: bind
        target: "/usr/local/bin/lang.config"
        source: "./lang.config"
      - type: bind
        target: "/usr/local/bin/vpn_server.config"
        source: "./vpn_server.config"
      - type: bind
        target: "/usr/local/bin/chain_certs"
        source: "./data/chain_certs"
