FROM debian:bookworm
RUN apt update; apt -y install wget

WORKDIR /usr/local/src
RUN wget https://jp.softether-download.com/files/softether/v4.43-9799-beta-2023.08.31-tree/Linux/SoftEther_VPN_Server/64bit_-_ARM_64bit/softether-vpnserver-v4.43-9799-beta-2023.08.31-linux-arm64-64bit.tar.gz -O se.tar.gz
RUN tar xzvf se.tar.gz
RUN sudo mv vpnserver /usr/local/bin

EXPOSE 443/tcp 992/tcp 1194/tcp 1194/udp 5555/tcp 500/udp 4500/udp
ENTRYPOINT ["/usr/local/bin/vpnserver", "execsvc"]
