FROM ubuntu

RUN apt update; apt -y install cmake gcc g++ make pkgconf libncurses5-dev libssl-dev libsodium-dev libreadline-dev zlib1g-dev git

WORKDIR /src

RUN git clone https://github.com/SoftEtherVPN/SoftEtherVPN.git

WORKDIR /src/SoftEtherVPN
RUN git submodule init && git submodule update
RUN CMAKE_FLAGS="-DSKIP_CPU_FEATURES" ./configure
RUN make -C build
RUN make -C build install

ENTRYPOINT ["vpnserver", "execsvc"]
